"use strict";
const SAVE_KEY="cardEmpireV4";
const rarities={Common:7,Uncommon:16,Rare:38,Epic:105,Legendary:280};
const catalog=[
["monster","Mossback Guardian","Earth","Common","🐢","#22c55e","#064e3b"],["monster","Glimmer Imp","Spark","Common","⚡","#f97316","#713f12"],["monster","Tunnel Hyena","Beast","Common","🐾","#a16207","#3f2d12"],["monster","Ember Drake","Fire","Uncommon","🐉","#ef4444","#4c0519"],["monster","Coral Siren","Water","Uncommon","🧜‍♀️","#06b6d4","#164e63"],["monster","Thorn Stalker","Nature","Uncommon","🐆","#16a34a","#052e16"],["monster","Storm Jackal","Lightning","Rare","🐺","#60a5fa","#172554"],["monster","Lunar Moth","Psychic","Rare","🦋","#818cf8","#1e1b4b"],["monster","Frost Manticore","Ice","Rare","🦁","#67e8f9","#164e63"],["monster","Void Serpent","Shadow","Epic","🐍","#a855f7","#2e1065"],["monster","Solar Phoenix","Light","Epic","🦅","#facc15","#7c2d12"],["monster","Abyssal Titan","Abyss","Legendary","🗿","#2563eb","#172554"],["monster","Celestial Chimera","Cosmic","Legendary","🦄","#f472b6","#3b0764"],
["sports","Nico Alvarez RC","Baseball Prospect","Common","⚾","#3b82f6","#0f3b75","24","Nico A."],["sports","Marcus Steele","Baseball All-Star","Uncommon","⚾","#2563eb","#172554","08","M. Steele"],["sports","Carter Voss","Baseball Superstar","Epic","⚾","#0ea5e9","#082f49","27","Carter Voss"],["sports","Eddie Comet Navarro","Baseball Hall of Fame","Legendary","⚾","#eab308","#451a03","44","Comet"],["sports","Trey Holloway RC","Basketball Prospect","Common","🏀","#f97316","#7c2d12","12","Trey H."],["sports","Andre Cross","Basketball All-Star","Uncommon","🏀","#ea580c","#431407","03","A. Cross"],["sports","Dominique Fox","Basketball Superstar","Epic","🏀","#f97316","#431407","23","Dom Fox"],["sports","Isaiah Skyline Turner","Basketball Hall of Fame","Legendary","🏀","#8b5cf6","#2e1065","34","Skyline"],["sports","Darius Reed RC","Football Prospect","Common","🏈","#a16207","#3f2a0b","18","D. Reed"],["sports","Talon Price","Football All-Star","Uncommon","🏈","#ca8a04","#422006","11","Talon P."],["sports","Xavier Stone","Football Superstar","Epic","🏈","#84cc16","#1a2e05","07","X. Stone"],["sports","Ray Iron Mile Maddox","Football Hall of Fame","Legendary","🏈","#f59e0b","#451a03","80","Iron Mile"],["sports","Luca Moretti RC","Soccer Prospect","Common","⚽","#22c55e","#14532d","19","L. Moretti"],["sports","Nico Duarte","Soccer All-Star","Uncommon","⚽","#16a34a","#052e16","10","N. Duarte"],["sports","Alejandro Vale","Soccer Superstar","Epic","⚽","#14b8a6","#042f2e","09","A. Vale"],["sports","Marco Golden Silva","Soccer Hall of Fame","Legendary","⚽","#facc15","#422006","11","Golden M"]];
const $=s=>document.querySelector(s),app=$('#app'),sheet=$('#sheet'),reveal=$('#reveal'),toastEl=$('#toast');
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const fresh=()=>({cash:100,inv:[],sold:0,earnings:0,chases:0,premium:false,nextId:1,prints:{}});
let state=fresh();
function load(){try{let raw=localStorage.getItem(SAVE_KEY);if(raw){let saved=JSON.parse(raw);state=Object.assign(fresh(),saved)}}catch(e){state=fresh()}}
function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state))}catch(e){}}
function itemPool(premium=false){if(!premium)return catalog.filter(x=>['Common','Uncommon'].includes(x[3]));return catalog.filter(x=>['Rare','Epic','Legendary'].includes(x[3]))}
function chooseItem(premium){let pool=itemPool(premium);let rarity=premium?(Math.random()<.5?'Rare':Math.random()<.78?'Epic':'Legendary'):(Math.random()<.62?'Common':'Uncommon');let options=pool.filter(x=>x[3]===rarity);return options[Math.floor(Math.random()*options.length)]}
function variantFor(item,premium){let r=item[3],x=Math.random();if(item[0]==='monster'){if(r==='Common')return x<.08?['Full Art',1.32]:['Base',1];if(r==='Uncommon')return x<.14?['Full Art',1.35]:x<.19?['Alt Art',1.5]:['Base',1];if(r==='Rare')return x<.23?['Full Art',1.4]:x<.32?['Alt Art',1.58]:['Base',1];if(r==='Epic')return x<.3?['Full Art',1.48]:x<.44?['Alt Art',1.72]:x<.48?['Secret Art',2.1]:['Base',1];return x<.32?['Full Art',1.6]:x<.49?['Alt Art',1.9]:x<.54?['Secret Art',2.4]:['Base',1]}let chance=rarities[r]>=100?[.42,.29,.19,.08,.02]:r==='Epic'?[.55,.24,.15,.05,.01]:r==='Uncommon'?[.72,.2,.07,.01,0]:[.83,.14,.03,0,0];if(premium)chance=[Math.max(.1,chance[0]-.25),chance[1]+.08,chance[2]+.09,chance[3]+.06,chance[4]+.02];let roll=Math.random(),total=0;let labels=['Base','Numbered','Autograph','Auto Numbered','One of One'];let boosts=[1,1.3,1.48,1.85,3];for(let i=0;i<labels.length;i++){total+=chance[i];if(roll<total)return[labels[i],boosts[i]]}return['Base',1]}
function serialFor(item,variant){if(!['Numbered','Auto Numbered'].includes(variant))return variant==='One of One'?'1/1':'';let max={Common:199,Uncommon:149,Rare:99,Epic:25,Legendary:10}[item[3]];let key=item[1]+variant;state.prints[key]=(state.prints[key]||0)%max+1;return state.prints[key]+'/'+max}
function makeCard(premium){let item=chooseItem(premium),[variant,boost]=variantFor(item,premium),condition=Math.random()<.12?'Gem Mint':Math.random()<.33?'Near Mint':Math.random()<.67?'Good':'Played';let conditionBoost={Played:.55,Good:.78,'Near Mint':1,'Gem Mint':1.35}[condition];return{id:state.nextId++,kind:item[0],name:item[1],line:item[2],rarity:item[3],icon:item[4],one:item[5],two:item[6],number:item[7]||'',signature:item[8]||'',variant,serial:serialFor(item,variant),condition,value:Math.max(2,Math.round(rarities[item[3]]*boost*conditionBoost*(premium?1.35:1)*(0.85+Math.random()*.35)))}}
function face(c){let special=c.variant!=='Base';return `<div class="face ${c.rarity}" style="--one:${c.one};--two:${c.two}"><div class="ribbon">${c.line} · ${c.rarity}</div>${special?`<div class="variant-tag">${c.variant}</div>`:''}<div class="art"><span class="glyph">${c.icon}</span></div>${c.serial?`<span class="serial">${c.serial}</span>`:''}${['Autograph','Auto Numbered','One of One'].includes(c.variant)&&c.signature?`<span class="autograph">${c.signature}</span>`:''}<div class="name-line"><div class="name">${c.name}</div><div class="cond">${c.condition}${c.number?' · #'+c.number:''}</div></div></div>`}
function render(){let chaseCount=state.inv.filter(c=>c.variant!=='Base').length;app.innerHTML=`<div class="app"><header class="top"><h1 class="brand">Card <b>Empire</b></h1><div class="top-actions"><div class="chips"><span class="chip cash">${money(state.cash)}</span><span class="chip">🃏 ${state.inv.length}</span></div><button class="icon-btn" data-action="reset" aria-label="Reset game">↻</button></div></header><section class="hero"><div><p class="eyebrow">Collector mode</p><h2>Rip packs.<br>Chase hits.</h2><p>Build your binder through rare art, autographs, serial numbers, and smart sales.</p></div><div class="pack pack-face"><div>CE</div></div></section><div class="shop"><div class="product"><strong>Starter Pack</strong><span>5 cards · $25</span><button data-pack="starter" ${state.cash<25?'disabled':''}>Open $25</button></div><div class="product premium"><strong>Premium Chase</strong><span>8 cards · $85 · ${state.premium?'Unlocked':'10 sales'}</span><button data-pack="premium" ${state.cash<85||!state.premium?'disabled':''}>Open $85</button></div></div><div class="section-title"><h3>Your Binder</h3><span>${state.inv.length} cards · ${chaseCount} chases</span></div><section class="binder">${state.inv.length?state.inv.map(c=>`<button class="card ${c.variant==='Full Art'?'full-art':c.variant==='Alt Art'?'alt-art':c.variant==='Secret Art'?'secret-art':''}" data-card="${c.id}">${face(c)}</button>`).join(''):'<div class="empty">Open a pack to start your collection.</div>'}</section></div>`}
function toast(message){toastEl.textContent=message;toastEl.classList.add('show');clearTimeout(toastEl.timer);toastEl.timer=setTimeout(()=>toastEl.classList.remove('show'),2200)}
let queue=[],qIndex=0;
function showReveal(){let c=queue[qIndex];reveal.className='reveal show';reveal.setAttribute('aria-hidden','false');reveal.innerHTML=`<div class="reveal-box"><div class="card ${c.variant==='Full Art'?'full-art':c.variant==='Alt Art'?'alt-art':c.variant==='Secret Art'?'secret-art':''}">${face(c)}</div><div class="reveal-help">${qIndex<queue.length-1?'Tap for next card':'Tap to add pack to binder'}</div></div>`}
function finishReveal(){state.inv.unshift(...queue);queue=[];qIndex=0;reveal.className='reveal';reveal.setAttribute('aria-hidden','true');reveal.innerHTML='';save();render();toast('Pack added to binder')}
function buyPack(type){let premium=type==='premium',cost=premium?85:25;if(state.cash<cost||(premium&&!state.premium))return;state.cash-=cost;queue=Array.from({length:premium?8:5},()=>makeCard(premium));qIndex=0;save();render();showReveal()}
function closeSheet(){sheet.className='sheet';sheet.setAttribute('aria-hidden','true');sheet.innerHTML=''}
function inspect(id){let c=state.inv.find(x=>x.id===id);if(!c)return;let offer=Math.round(c.value);sheet.innerHTML=`<div class="panel"><div class="detail"><div class="card ${c.variant==='Full Art'?'full-art':c.variant==='Alt Art'?'alt-art':c.variant==='Secret Art'?'secret-art':''}">${face(c)}</div><div><h3>${c.name}</h3><p>${c.line}</p><p>${c.variant}${c.serial?' · '+c.serial:''}</p></div></div><div class="detail-rows"><div class="detail-row"><span>Condition</span><b>${c.condition}</b></div><div class="detail-row"><span>Estimate</span><b>${money(c.value*.85)}–${money(c.value*1.15)}</b></div><div class="detail-row"><span>Buyer offer</span><b>${money(offer)}</b></div></div><div class="actions"><button class="keep" data-action="keep">Hold</button><button class="sell" data-action="sell" data-id="${c.id}">Sell ${money(offer)}</button></div></div>`;sheet.className='sheet show';sheet.setAttribute('aria-hidden','false')}
function sell(id){let index=state.inv.findIndex(c=>c.id===id);if(index<0)return;let c=state.inv[index];state.inv.splice(index,1);state.cash+=c.value;state.sold++;state.earnings+=c.value;if(!state.premium&&state.sold>=10){state.premium=true;toast('Premium Chase unlocked')}else{toast('Sold for '+money(c.value))}closeSheet();save();render()}
function reset(){if(!window.confirm('Reset Card Empire and erase your saved binder?'))return;state=fresh();localStorage.removeItem(SAVE_KEY);closeSheet();reveal.className='reveal';queue=[];render();toast('New collection started')}
document.addEventListener('click',event=>{let pack=event.target.closest('[data-pack]');if(pack)buyPack(pack.dataset.pack);let cardBtn=event.target.closest('[data-card]');if(cardBtn)inspect(Number(cardBtn.dataset.card));let action=event.target.closest('[data-action]');if(action?.dataset.action==='reset')reset();if(action?.dataset.action==='keep')closeSheet();if(action?.dataset.action==='sell')sell(Number(action.dataset.id));if(event.target===sheet)closeSheet()});
reveal.addEventListener('click',()=>{if(!queue.length)return;if(qIndex<queue.length-1){qIndex++;showReveal()}else finishReveal()});
window.addEventListener('beforeunload',save);
load();render();
